### ISSUE TITLE
jekyll 3.1.0 | Error:  undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by illus0r** [fauno/jekyll-pandoc-multiple-formats#21]
```
Configuration file: _config.yml
Configuration file: _customer-details/client/_config.yml
            Source: /Users/ivan/prj/company
       Destination: /Users/ivan/prj/company/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
jekyll 3.1.0 | Error:  undefined method `[]' for nil:NilClass
2016-02-05T13:29:38.048Z [jekyll] ERROR Exited with code 1
```

Should it work with this version?

**Comment by fauno** [comment]
hey, we've been using it with jekyll 2, but we're on the process of
revamping it so it works with jekyll 3 and has several other features :)

-- 
http://endefensadelsl.org/

**Comment by illus0r** [comment]
thanks, @fauno, I should add I'm new to jekyll plugins, error can be on my side and be merely stupid.
arrr, forgot to update `_config.yml` and install `pandoc`.

Now I got some warnings, but it works
```
       Deprecation: posts.each should be changed to posts.docs.each.
                    Called by /Library/Ruby/Gems/2.0.0/gems/jekyll-pandoc-multiple-formats-0.0.7/lib/jekyll-pandoc-multiple-formats.rb:19:in `block in generate'.
       Deprecation: posts.each should be changed to posts.docs.each.
                    Called by /Library/Ruby/Gems/2.0.0/gems/jekyll-pandoc-multiple-formats-0.0.7/lib/jekyll-pandoc-multiple-formats.rb:19:in `block in generate'.
       Deprecation: posts.each should be changed to posts.docs.each.
                    Called by /Library/Ruby/Gems/2.0.0/gems/jekyll-pandoc-multiple-formats-0.0.7/lib/jekyll-pandoc-multiple-formats.rb:19:in `block in generate'.
                    done in 30.727 seconds.
```

Sorry, I'll close
