### ISSUE TITLE
jekyll 3.0.3 | Error:  Liquid error (line 95): invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by ickc** [fauno/jekyll-pandoc-multiple-formats#22]
Hi, once I set this gem up in my Jekyll site, and when I `bundle exec jekyll serve` it, it has the error:

```bash
jekyll 3.0.3 | Error:  Liquid error (line 95): invalid byte sequence in US-ASCII
```

But there wasn't such a problem before using this gem.

Any idea how might this be fixed?

Thanks.

**Comment by fauno** [comment]
can you run it with --trace so it spits out more details?

-- 
http://vqfe4xmhxzi7w2uv.onion/

**Comment by ickc** [comment]
Is it this one?

```bash
  Liquid Exception: Liquid error (line 95): invalid byte sequence in US-ASCII in _includes/head.html, included in _layouts/post.html
~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/lib/jekyll/tags/include.rb:133:in `rescue in render': Liquid error (line 95): invalid byte sequence in US-ASCII (Jekyll::Tags::IncludeTagError)
	from ~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/lib/jekyll/tags/include.rb:125:in `render'
	from ~/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	from ~/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from ~/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	from ~/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from ~/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	from ~/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	from ~/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	from ~/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
	from ~/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
	from ~/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
	from ~/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
	from ~/.rvm/gems/ruby-2.2.1/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
	from ~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
	from ~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/lib/jekyll/liquid_renderer/file.rb:36:in `measure_bytes'
	from ~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
	from ~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
	from ~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
	from ~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/lib/jekyll/renderer.rb:105:in `render_liquid'
	from ~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/lib/jekyll/renderer.rb:147:in `place_in_layouts'
	from ~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/lib/jekyll/renderer.rb:69:in `run'
	from ~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/lib/jekyll/site.rb:171:in `block (2 levels) in render'
	from ~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/lib/jekyll/site.rb:169:in `each'
	from ~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/lib/jekyll/site.rb:169:in `block in render'
	from ~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/lib/jekyll/site.rb:168:in `each'
	from ~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/lib/jekyll/site.rb:168:in `render'
	from ~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/lib/jekyll/site.rb:59:in `process'
	from ~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/lib/jekyll/command.rb:28:in `process_site'
	from ~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/lib/jekyll/commands/build.rb:60:in `build'
	from ~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/lib/jekyll/commands/build.rb:35:in `process'
	from ~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from ~/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `call'
	from ~/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from ~/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from ~/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from ~/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from ~/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from ~/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.3/bin/jekyll:17:in `<top (required)>'
	from ~/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `load'
	from ~/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `<main>'
	from ~/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from ~/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by fauno** [comment]
ickc <notifications@github.com> writes:

> Is it this one?
>
> ```bash
>   Liquid Exception: Liquid error (line 95): invalid byte sequence in US-ASCII in _includes/head.html, included in _layouts/post.html

this doesn't seem to be an error of this plugin :)

which version have you installed?

-- 
 D

**Comment by ickc** [comment]
jekyll 3.0.3.

I don't understand why. It was ok when I `bundle exec jekyll serve` but after I added this plugin it has the above error.

Anyway, I might try it again in the future. I'm closing the issue now since it is unclear what's the origin of the problem. Thanks for your help anyway!

**Comment by fauno** [comment]
ickc <notifications@github.com> writes:

> jekyll 3.0.3.

i meant this plugin version :)

can you try with the develop branch?  if you're unsure how to run it,
check edsl/endefensadelsl.org, the Gemfile and the _plugins/bundler.rb

it's the development version with a lot of changes, so checkout the new
configuration format

-- 
http://utopia.partidopirata.com.ar/

**Comment by ickc** [comment]
I tried it again and it works now.

I basically set the locale by

```bash
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
```

I'm not sure why this is not needed before this plugin is used. But I think I recall that the Ruby has some problem with it. Searching the error in Jekyll's issues has quite a few hits.

Thanks!
