### ISSUE TITLE
undefined method `matches` for #<Jekyll::Converters::Markdown:0x00000001d9e4e0> (NoMethodError)

### ISSUE THREAD

**Issue by lingnand** [fauno/jekyll-pandoc-multiple-formats#3]
I'm using a Octopress+Jekyll setup and placed `pandoc.rb` under `<web-directory>/plugins`; I've changed `_config.yml` as suggested in readme.md.

But as soon as I run `jekyll build` I get the following

>  Configuration from /home/lingnan/Dropbox/lynnard.github.com/_config.yml
> Building site: source -> build
> /home/lingnan/.gem/ruby/2.0.0/gems/jekyll-0.12.0/lib/jekyll/convertible.rb:62:in `block in converter': undefined method`matches' for #Jekyll::Converters::Markdown:0x00000001d9e4e0 (NoMethodError)
>         from /home/lingnan/.gem/ruby/2.0.0/gems/jekyll-0.12.0/lib/jekyll/convertible.rb:62:in `each'
>         from /home/lingnan/.gem/ruby/2.0.0/gems/jekyll-0.12.0/lib/jekyll/convertible.rb:62:in`find'
>         from /home/lingnan/.gem/ruby/2.0.0/gems/jekyll-0.12.0/lib/jekyll/convertible.rb:62:in `converter'
>         from /home/lingnan/.gem/ruby/2.0.0/gems/jekyll-0.12.0/lib/jekyll/convertible.rb:54:in`output_ext'
>         from /home/lingnan/.gem/ruby/2.0.0/gems/jekyll-0.12.0/lib/jekyll/page.rb:145:in `html?'
>         from /home/lingnan/.gem/ruby/2.0.0/gems/jekyll-0.12.0/lib/jekyll/site.rb:300:in`block in site_payload'
>         from /home/lingnan/.gem/ruby/2.0.0/gems/jekyll-0.12.0/lib/jekyll/site.rb:300:in `reject'
>         from /home/lingnan/.gem/ruby/2.0.0/gems/jekyll-0.12.0/lib/jekyll/site.rb:300:in`site_payload'
>         from /home/lingnan/Dropbox/lynnard.github.com/plugins/pagination.rb:33:in `paginate'
>         from /home/lingnan/Dropbox/lynnard.github.com/plugins/pagination.rb:14:in`block in generate'
>         from /home/lingnan/Dropbox/lynnard.github.com/plugins/pagination.rb:13:in `each'

**Comment by XiZepu** [comment]
I use jekyll 2.2.0, and the error message like this:

``zepu@zepu-thinkpad-e420:~/Twenty-Jekyll-Theme$ jekyll -v``

    jekyll 2.2.0

use jekyll:

``zepu@zepu-thinkpad-e420:~/Twenty-Jekyll-Theme$ jekyll serve``

    Configuration file: /home/zepu/Twenty-Jekyll-Theme/_config.yml
                Source: /home/zepu/Twenty-Jekyll-Theme
           Destination: /home/zepu/Twenty-Jekyll-Theme/_site
          Generating... 
      Conversion error: There was an error converting '_posts/2014-08-07-first-post.markdown/#excerpt'.
    jekyll 2.2.0 | Error:  undefined method `keys' for nil:NilClass

I try to update jekyll
``zepu@zepu-thinkpad-e420:~/Twenty-Jekyll-Theme$ gem update jekyll``

    Updating installed gems
    Nothing to update

**Comment by fauno** [comment]
@XiZepu i don't know why i don't get email notifications, sorry i never replied! :/

i think we fixed your issue a while ago, it had to do with excerpts being included on the yaml metadata but actually being a ruby object, so we skipped it
