### ISSUE TITLE
Bundler issues

### ISSUE THREAD

**Issue by HaoZeke** [fauno/jekyll-pandoc-multiple-formats#32]
Hi.
I guess this needs to be updated to build against a newer jekyll?

I get 

```bash
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    jekyll (= 3.5.0)

    jekyll-pandoc-multiple-formats (= 0.2.9.1) was resolved to 0.2.9.1, which depends on
      jekyll (~> 3.3.0)

```

**Comment by fauno** [comment]
cna you try adding it like this in your Gemfile?  i bumped it to jekyll
3.6 last week but haven't had the time to check.  it worked ok on the
test build i did.

```ruby
gem 'jekyll-pandoc-multiple-formats', github: 'edsl/jekyll-pandoc-multiple-formats', branch: 'develop'
```

-- 
P)

**Comment by HaoZeke** [comment]
Same issue as attempting to force usage for jekyll 3.6, namely:

```bash
jekyll serve                                                            1 
Configuration file: /home/haozeke/Github/Pandoc/jekyllNotes/_config.yml
            Source: /home/haozeke/Github/Pandoc/jekyllNotes
       Destination: /home/haozeke/Github/Pandoc/jekyllNotes/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.6.2 | Error:  no implicit conversion of nil into Hash
```

I suppose there have been some changes to the structure of jekyll?

**Comment by fauno** [comment]
can you add `--trace` so we have more context?

-- 
:{

**Comment by HaoZeke** [comment]
Sure, my pleasure :D 

```ruby
jekyll build --trace
Configuration file: /home/haozeke/Github/Pandoc/jekyllNotes/_config.yml
            Source: /home/haozeke/Github/Pandoc/jekyllNotes
       Destination: /home/haozeke/Github/Pandoc/jekyllNotes/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/home/haozeke/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/utils.rb:315:in `merge!': no implicit conversion of nil into Hash (TypeError)
	from /home/haozeke/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/utils.rb:315:in `merge_values'
	from /home/haozeke/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/utils.rb:49:in `deep_merge_hashes!'
	from /home/haozeke/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/utils.rb:36:in `deep_merge_hashes'
	from /home/haozeke/.rvm/gems/ruby-2.4.0/bundler/gems/jekyll-pandoc-multiple-formats-7b6e7fbd2ce9/lib/jekyll-pandoc-multiple-formats/config.rb:20:in `initialize'
	from /home/haozeke/.rvm/gems/ruby-2.4.0/bundler/gems/jekyll-pandoc-multiple-formats-7b6e7fbd2ce9/lib/jekyll-pandoc-multiple-formats/generator.rb:33:in `new'
	from /home/haozeke/.rvm/gems/ruby-2.4.0/bundler/gems/jekyll-pandoc-multiple-formats-7b6e7fbd2ce9/lib/jekyll-pandoc-multiple-formats/generator.rb:33:in `generate'
	from /home/haozeke/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:176:in `block in generate'
	from /home/haozeke/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:174:in `each'
	from /home/haozeke/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:174:in `generate'
	from /home/haozeke/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/site.rb:72:in `process'
	from /home/haozeke/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/command.rb:28:in `process_site'
	from /home/haozeke/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:65:in `build'
	from /home/haozeke/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:36:in `process'
	from /home/haozeke/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/jekyll-3.6.2/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/haozeke/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /home/haozeke/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /home/haozeke/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /home/haozeke/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /home/haozeke/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /home/haozeke/.rvm/gems/ruby-2.4.0@global/gems/jekyll-3.6.2/exe/jekyll:15:in `<top (required)>'
	from /home/haozeke/.rvm/gems/ruby-2.4.0/bin/jekyll:22:in `load'
	from /home/haozeke/.rvm/gems/ruby-2.4.0/bin/jekyll:22:in `<main>'
	from /home/haozeke/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/haozeke/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by fauno** [comment]
mmm can you try with ruby 2.3?  we haven't been using 2.4, just to
discard it's a ruby issue

-- 
 D
